<script setup lang="ts">
const libraryPageCache = useState('library-pages-v2', () => ({}))
const route = useRoute()
const { data: manga, error: fetchError, refresh } = await useFetch<any>(() => `/api/manga/${route.params.slug}`)
const downloading = ref(false), downloadingPage = ref(''), notice = ref(''), error = ref('')
const downloaded = computed(() => manga.value?.mangaPages.filter((page: any) => page.downloadStatus === 'COMPLETED') || [])
const authors = computed(() => String(manga.value?.author || '').split(',').map(author => author.trim()).filter(Boolean))
const searchLink = (query: string) => ({ path: '/search', query: { q: query, adult: '1' } })
useVisiblePolling(() => { if (manga.value?.repairPending || manga.value?.mangaPages.some((page: any) => ['PENDING', 'DOWNLOADING'].includes(page.downloadStatus))) return refresh() }, 5000)
async function download(sourcePageIds?: string[]) { if (!manga.value) return; downloading.value = !sourcePageIds; downloadingPage.value = sourcePageIds?.[0] || ''; try { const result: any = await $fetch(`/api/downloads/${manga.value.sourceSite}`, { method: 'POST', body: { sourceNovelId: manga.value.sourceNovelId, sourcePageIds } }); libraryPageCache.value = {}; notice.value = result.queued ? `${result.queued} pages queued.` : 'Already downloaded or queued.'; await refresh() } catch (e: any) { error.value = e?.data?.statusMessage || e?.message || 'Download failed.' } finally { downloading.value = false; downloadingPage.value = '' } }
</script>

<template>
  <PageError v-if="fetchError" :error="fetchError" @retry="refresh()" />
  <div v-else-if="manga" class="mx-auto max-w-7xl px-5 py-10 md:py-14">
    <LibraryBreadcrumbs :title="manga.titleTranslated || manga.titleOriginal" :library="manga.libraryEntries?.[0]?.library" media="MANGA" />
    <div class="mb-6"><NuxtLink :to="`/manga/${manga.slug}/read`" class="btn btn-primary">Read / stream manga</NuxtLink><span class="ml-3 text-xs text-muted">Downloaded pages use local files; others load directly from the source.</span></div>
    <section class="grid gap-8 lg:grid-cols-[220px_1fr]"><div class="mx-auto aspect-[2/3] w-44 overflow-hidden rounded-2xl bg-white/5 lg:mx-0 lg:w-full"><BookCover :src="manga.coverPath ? `/api/novels/${manga.id}/cover?v=${encodeURIComponent(manga.updatedAt)}` : manga.coverUrl" :title="manga.titleOriginal" class="h-full w-full object-cover" /></div><div class="flex flex-col justify-center"><div class="flex gap-2"><span class="badge badge-muted">Manga</span><span v-if="manga.contentRating === 'ADULT'" class="badge badge-bad">Adult</span></div><h1 class="mt-5 font-serif text-4xl font-semibold leading-tight md:text-6xl">{{ manga.titleOriginal }}</h1><div class="mt-4 flex flex-wrap items-center gap-2 text-sm text-muted"><span v-if="!authors.length">Unknown artist</span><NuxtLink v-for="author in authors" :key="author" :to="searchLink(author)" class="rounded-full border border-gold/25 bg-gold/10 px-3 py-1 text-gold transition hover:border-gold/60 hover:bg-gold/15">{{ author }}</NuxtLink><span>· {{ manga.wordCountLabel }}</span></div><p v-if="manga.description" class="mt-6 max-w-4xl text-sm leading-7 text-muted">{{ manga.description }}</p><div v-if="manga.tags?.length" class="mt-5 flex flex-wrap gap-2"><NuxtLink v-for="tag in manga.tags" :key="tag" :to="searchLink(tag)" class="rounded-full border border-white/10 bg-white/[.035] px-3 py-1.5 text-xs text-muted transition hover:border-gold/40 hover:text-gold">{{ tag }}</NuxtLink></div><div class="mt-7 flex flex-wrap gap-3"><NuxtLink v-if="downloaded.length" :to="`/manga/${manga.slug}/read`" class="btn btn-primary">Read downloaded pages</NuxtLink><button class="btn" :class="downloaded.length ? 'btn-quiet' : 'btn-primary'" :disabled="downloading" @click="download()">{{ downloading ? 'Queueing…' : 'Download manga' }}</button><NuxtLink :to="`/sources/${manga.sourceSite}/books/${manga.sourceNovelId}`" class="btn btn-quiet">View source entry</NuxtLink></div><p v-if="notice" class="mt-4 text-sm text-gold">{{ notice }}</p><p v-if="error" class="mt-4 text-sm text-[#efa58b]">{{ error }}</p></div></section>
    <section class="mt-14"><div class="mb-5"><p class="text-xs uppercase tracking-[.2em] text-muted">Pages</p><h2 class="mt-2 font-serif text-3xl font-semibold">{{ manga.mangaPages.length }} indexed · {{ downloaded.length }} downloaded</h2></div><div v-if="manga.mangaPages.length" class="grid grid-cols-3 gap-3 sm:grid-cols-5 lg:grid-cols-8"><div v-for="page in manga.mangaPages" :key="page.id" class="surface overflow-hidden rounded-xl"><NuxtLink :to="`/manga/${manga.slug}/read?page=${page.position}`" class="group block aspect-[2/3] bg-white/5" :aria-label="`Read from page ${page.position}`"><img v-if="page.downloadStatus === 'COMPLETED'" :src="`/api/manga/pages/${page.id}/image?v=${encodeURIComponent(page.downloadedAt || page.updatedAt)}`" :alt="`Page ${page.position}`" loading="lazy" class="h-full w-full object-cover transition group-hover:scale-[1.02]" /><img v-else-if="page.thumbnailUrl" :src="page.thumbnailUrl" :alt="`Page ${page.position}`" loading="lazy" class="h-full w-full object-cover opacity-75 transition group-hover:opacity-80" /></NuxtLink><button class="w-full px-2 py-2 text-xs" :class="page.downloadStatus === 'COMPLETED' ? 'text-[#9fd6b0]' : 'text-gold'" :disabled="['PENDING','DOWNLOADING','COMPLETED'].includes(page.downloadStatus) || downloadingPage === page.sourcePageId" @click="download([page.sourcePageId])">{{ page.downloadStatus === 'COMPLETED' ? 'Downloaded' : page.downloadStatus === 'FAILED' ? 'Retry' : page.downloadStatus === 'DOWNLOADING' ? 'Downloading' : page.downloadStatus === 'PENDING' ? 'Queued' : 'Download' }}</button></div></div><div v-else class="surface rounded-2xl p-10 text-center text-muted">Bookmark metadata only. Download the manga to index its pages.</div></section>
  </div>
</template>
